export const ECOMSAI_PLATFORM_USER_ROLE = "PLATFORM"
export const ECOMSAI_PLATFORM_USER_ID = 0
export const ECOMSAI_PLATFORM_TENANT_ID = 0
export const ECOMSAI_PLATFORM_STORE_ID = 0
export const ECOMSAI_PLATFORM_USER_NAME = "ECOMSAI"

export const ECOMSAI_PLATFORM_SUPPORT_USER_ROLE = "PLATFORM_SUPPORT"
export const CRAFT_BUILDER_MAINTAINER_USER_ROLE = "CRAFT_BUILDER_MAINTAINER"
